apiVersion: apps/v1  # Api version
kind: Deployment # kubernetes resource kind we are creating
metadata:
 name: kubernetespractice-deployment
spec:
 selector:
  matchLabels:
   app: kubernetespractice
 replicas: 1 
 template:
  metadata:
   labels:
    app: kubernetespractice
  spec:
   containers:
    - name: kubernetespractice
      image: kubernetespractice:1.0
      imagePullPolicy: IfNotPresent
      ports:
       - containerPort: 8080